---
title: "Lab 1"
author: "Nathanael Reese"
date: 01.18.2023
output: html_document
---

```{r setup, include = FALSE}
```

# Tasks

## Task 1

``` {r}
getwd()
```

## Task 2

``` {r} 
ddt <- read.csv("DDT.csv")
head(ddt, n = 6) 
```

## Task 3

 ``` {r}
qual = ddt[, c(1 , 3)]
head(qual, n=0)
quant = ddt[, c(2 , 4, 5, 6)]
head(quant, n=0)
speciesVector <- c(with(ddt, table(SPECIES)))
print("Number of Species of Fish")
print(length(unique(speciesVector)))
bigbass=with(ddt, ddt[WEIGHT>800 & SPECIES=="LMBASS",])
print(bigbass)
riverscm = with(ddt, ddt[DDT>4.0 & RIVER=="SCM",])
print(riverscm)
mean(ddt[["LENGTH"]])
print(sd(ddt$WEIGHT))

 ```

## Task 4

**Rivers Table**
```{r}
rt =table(ddt[, c(1)])
print(rt)
```
**Color Coded Bar Plot of Rivers**
```{r}
barplot(rt,beside=TRUE,col=rainbow(4))
```

**Table of Rivers Crossed with Species of Fish**
```{r}
with(ddt,ddt[order(RIVER,SPECIES),])

```

## Task 5
```{r}
st =table(ddt[, c(3)])
```
**Pie Chart of Species**
```{r}
pie(st)
```

**Pie Chart of Rivers**
```{r}
pie(rt)
```

## Task 6
**Boxplot of DDT**
```{r}
with(ddt,boxplot(DDT,ylab="DDT",col="Green",notch=TRUE))
```

**Boxplot of Weight**
```{r}
with(ddt,boxplot(WEIGHT,ylab="WEIGHT",col="Red",notch=TRUE))

```

**Boxplot of Length**
```{r}
with(ddt,boxplot(LENGTH,ylab="LENGTH",col="Blue",notch=TRUE))
```

## Task 7

**Coplot of LENGTH Vs WEIGHT given RIVER**
```{r}
rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                        ifelse(RIVER=="LCM","Blue",
                               ifelse(RIVER=="SCM","Green","Black"))))

coplot(WEIGHT~LENGTH|RIVER,data=ddt,col=rivcol)

```

**Coplot of DDT Vs WEIGHT given SPECIES**

```{r}
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))

coplot(WEIGHT~DDT|SPECIES,data=ddt,col=fishcol)

```

## Task 8

**GGPLOT with name**
```{r}
library(dplyr)
library(ggplot2)
ddt%>%filter(LENGTH > 30)%>%mutate(AREA=LENGTH*WEIGHT)%>%ggplot(aes(x=SPECIES,y=WEIGHT,fill=RIVER))+geom_boxplot()+ggtitle("Nathanael Reese")
```

**Violin Plot with Name**
```{r}

ddt%>%filter(LENGTH > 10)%>%ggplot(aes(x=RIVER,y=LENGTH,fill=SPECIES))+geom_violin()+ggtitle("Nathanael Reese")
```

**Scatter Plot with Name**

```{r}
ddt%>%filter(WEIGHT > 200, LENGTH > 30, DDT < 300)%>%mutate(AREA=LENGTH*WEIGHT)%>%ggplot(aes(x=WEIGHT,y=LENGTH,fill=RIVER))+geom_point(size=2, shape=23)+ggtitle("Nathanael Reese")
```
